---
-    name: Update apt packages
     apt: 
         update_cache: yes
  
-    name: Install dependencies
     apt: 
         name:
             - apt-transport-https
             - ca-certificates
             - curl
             - gnupg
             - lsb-release
         state: present
         update_cache: yes

-    name: Add GPG key
     apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present
         
-    name: Add apt repository for stable version
     apt_repository:
         repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
         state: present
         
-    name: Install Docker
     apt:
         name: "{{ packages }}"
         state: present
         update_cache: yes
     vars:
         packages:
             - docker-ce
             - docker-ce-cli
             - containerd.io
              
             
             
             
        